import { Copy, Check, Download, Edit3, Sparkles, Activity, FileDown } from "lucide-react";
import { useState, useEffect } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { jsPDF } from "jspdf";

function TranscriptionBox({ transcript, isReviewMode, onEdit }) {
  const [copied, setCopied] = useState(false);
  const [displayText, setDisplayText] = useState("");
  const [isTyping, setIsTyping] = useState(false);

  useEffect(() => {
    if (transcript && !isReviewMode) { // Only type out if not in review mode
      setIsTyping(true);
      setDisplayText("");
      let i = 0;
      const interval = setInterval(() => {
        setDisplayText(transcript.slice(0, i));
        i++;
        if (i > transcript.length) {
          clearInterval(interval);
          setIsTyping(false);
        }
      }, 8); // Crisp typing speed
      return () => clearInterval(interval);
    } else if (transcript && isReviewMode) { // If in review mode, show full transcript immediately
      setDisplayText(transcript);
      setIsTyping(false);
    } else {
      setDisplayText("");
      setIsTyping(false);
    }
  }, [transcript, isReviewMode]);

  const copyToClipboard = () => {
    if (!transcript) return;
    navigator.clipboard.writeText(transcript);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const downloadPDF = () => {
    if (!transcript) return;
    
    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.getWidth();
    const margin = 20;
    const contentWidth = pageWidth - (margin * 2);
    
    // 1. Branding Header
    doc.setFillColor(79, 70, 229); // Indigo-600
    doc.rect(0, 0, pageWidth, 40, 'F');
    
    doc.setTextColor(255, 255, 255);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(24);
    doc.text("SpeechScribe", margin, 25);
    
    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    doc.text("Intelligence Extraction Unit", margin, 32);
    
    // 2. Metadata Section
    doc.setTextColor(100, 116, 139); // Slate-500
    doc.setFontSize(9);
    const dateStr = new Date().toLocaleString();
    doc.text(`Exported: ${dateStr}`, margin, 55);
    doc.text(`Status: Integrity Verified`, margin, 60);
    doc.text(`Classification: Secure Report`, margin, 65);
    
    // Divider
    doc.setDrawColor(226, 232, 240); // Slate-200
    doc.line(margin, 72, pageWidth - margin, 72);
    
    // 3. Body Content
    doc.setTextColor(30, 41, 59); // Slate-800
    doc.setFont("helvetica", "normal");
    doc.setFontSize(11);
    
    // Split text into lines that fit the page width
    const splitText = doc.splitTextToSize(transcript, contentWidth);
    
    // Add text with line height
    doc.text(splitText, margin, 85, {
      lineHeightFactor: 1.5
    });
    
    // 4. Footer
    const pageCount = doc.internal.getNumberOfPages();
    for(let i = 1; i <= pageCount; i++) {
      doc.setPage(i);
      doc.setFontSize(8);
      doc.setTextColor(148, 163, 184); // Slate-400
      doc.text(
        `Page ${i} of ${pageCount} • Generated by SpeechScribe AI`, 
        pageWidth / 2, 
        doc.internal.pageSize.getHeight() - 10, 
        { align: "center" }
      );
    }

    doc.save(`SpeechScribe_Transcript_${Date.now()}.pdf`);
  };

  return (
    <div className={`relative ${isReviewMode ? "min-h-[600px]" : "h-[400px] md:h-full md:flex-1 md:max-h-[500px]"}`}>
      <div className="card-clean h-full flex flex-col overflow-hidden bg-slate-900/40">
        {/* Header Toolbar - responsive wrap */}
        <div className="px-4 py-3 border-b border-white/5 bg-slate-950/40 flex flex-wrap items-center gap-2 justify-between">
          <div className="flex items-center gap-2 min-w-0">
            <div className={`w-1.5 h-1.5 flex-shrink-0 rounded-full ${isReviewMode ? "bg-indigo-500" : "bg-emerald-500 animate-pulse"}`} />
            <span className="text-[10px] font-black text-slate-500 uppercase tracking-widest truncate">
              {isReviewMode ? "Historical Archive" : "Live Stream"}
            </span>
          </div>

          <div className="flex items-center gap-2 flex-wrap">
            {isReviewMode && (
              <button
                onClick={onEdit}
                className="p-2 rounded-lg bg-indigo-500/10 text-indigo-400 hover:bg-indigo-500/20 transition-all border border-indigo-500/10 flex items-center gap-1.5 px-2.5"
              >
                <Edit3 size={13} />
                <span className="text-[9px] font-black uppercase tracking-widest whitespace-nowrap">Edit</span>
              </button>
            )}
            <button
              onClick={copyToClipboard}
              className="p-2 rounded-lg bg-white/5 text-slate-400 hover:text-white hover:bg-white/10 transition-all border border-white/5 flex items-center gap-1.5 px-2.5"
              title="Copy to Clipboard"
            >
              {copied ? <Check size={14} className="text-emerald-500" /> : <Copy size={14} />}
              <span className="text-[9px] font-black uppercase tracking-widest hidden sm:inline whitespace-nowrap">Copy</span>
            </button>
            <button
              onClick={downloadPDF}
              className="p-2 rounded-lg bg-indigo-500/10 text-indigo-400 hover:bg-indigo-500/20 transition-all border border-indigo-500/10 flex items-center gap-1.5 px-2.5"
              title="Download PDF Report"
            >
              <FileDown size={14} />
              <span className="text-[9px] font-black uppercase tracking-widest hidden sm:inline whitespace-nowrap">PDF</span>
            </button>
          </div>
        </div>

        {/* Content Area */}
        <div className="flex-1 p-8 overflow-y-auto custom-scrollbar relative">
          <AnimatePresence mode="wait">
            {!transcript ? (
              <motion.div
                key="empty"
                initial={{ opacity: 0 }}
                animate={{ opacity: 1 }}
                exit={{ opacity: 0 }}
                className="h-full flex flex-col items-center justify-center text-center opacity-20 grayscale"
              >
                <Sparkles size={48} className="mb-6 text-slate-600" />
                <p className="text-[10px] font-black uppercase tracking-[0.4em] text-slate-500">Awaiting Signal</p>
              </motion.div>
            ) : (
              <motion.div
                key="content"
                initial={{ opacity: 0 }}
                animate={{ opacity: 1 }}
                className="space-y-8"
              >
                <div className="prose prose-invert max-w-none">
                   <p className="text-slate-100 leading-[2] text-lg font-bold tracking-tight bg-clip-text">
                    {displayText}
                    {isTyping && (
                      <motion.span
                        animate={{ opacity: [0, 1, 0] }}
                        transition={{ repeat: Infinity, duration: 0.8 }}
                        className="inline-block w-1 h-5 ml-1 bg-indigo-500 align-middle"
                      />
                    )}
                  </p>
                </div>
              </motion.div>
            )}
          </AnimatePresence>
        </div>
        
        {transcript && (
          <div className="p-6 border-t border-white/5 bg-slate-950/20 flex justify-end">
            <button
               onClick={copyToClipboard}
               className={`group flex items-center gap-2.5 px-5 py-2.5 rounded-xl transition-all duration-300 border ${
                 copied 
                   ? "bg-emerald-500/10 text-emerald-500 border-emerald-500/20" 
                   : "bg-slate-800 text-slate-300 border-white/5 hover:bg-slate-700 hover:text-white"
               }`}
            >
              {copied ? (
                <>
                  <Check size={16} />
                  <span className="font-black text-[10px] uppercase tracking-widest">Copied</span>
                </>
              ) : (
                <>
                  <Copy size={16} className="group-hover:scale-110 transition-transform" />
                  <span className="font-black text-[10px] uppercase tracking-widest">Copy Text</span>
                </>
              )}
            </button>
          </div>
        )}
      </div>
    </div>
  );
}

export default TranscriptionBox;
